# Generated by Django 4.1 on 2023-05-13 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comments_create_date_alter_post_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 6, 38, 10, 428648, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 6, 38, 10, 428648, tzinfo=datetime.timezone.utc)),
        ),
    ]
