# Generated by Django 4.1 on 2023-05-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blog_post_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='current_date',
            new_name='created_date',
        ),
    ]
